BEGIN;

-- complaint_petition FK 잠시 해제 (테이블 재생성 대비)
DO $$
BEGIN
    IF to_regclass('public.complaint_petition') IS NOT NULL THEN
        EXECUTE 'ALTER TABLE complaint_petition DROP CONSTRAINT IF EXISTS fk_complaint_petition_location_department';
        -- 인라인 REFERENCES로 생성된 경우의 자동 이름도 드롭
        EXECUTE 'ALTER TABLE complaint_petition DROP CONSTRAINT IF EXISTS complaint_petition_location_department_id_fkey';
    END IF;
END $$;

-- 기존 매핑 테이블 초기화
DROP TABLE IF EXISTS location_department;
DROP TABLE IF EXISTS department;

-- 1) 카테고리 마스터 (테이블명/컬럼명은 기존 유지)
CREATE TABLE department (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(128) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL
);

-- 2) 시군구-카테고리 매핑 (테이블명/컬럼명은 기존 유지)
CREATE TABLE location_department (
    location_department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL REFERENCES location(location_id),
    department_id BIGINT NOT NULL REFERENCES department(department_id),
    location_department_email VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL,
    CONSTRAINT uq_location_department_pair UNIQUE (location_id, department_id)
);

CREATE INDEX idx_location_department_location_id
    ON location_department (location_id);

CREATE INDEX idx_location_department_department_id
    ON location_department (department_id);

-- 3) 카테고리 시드
INSERT INTO department (department_name) VALUES
    ('건축허가'),
    ('경제'),
    ('공통'),
    ('교통'),
    ('농업_축산'),
    ('문화_체육_관광'),
    ('보건소'),
    ('복지'),
    ('산림'),
    ('상하수도'),
    ('세무'),
    ('안전건설'),
    ('위생'),
    ('자동차'),
    ('정보통신'),
    ('토지'),
    ('행정'),
    ('환경미화');

-- 4) location 전체 x category 전체 매핑
INSERT INTO location_department (
    location_id,
    department_id,
    location_department_email,
    is_active
)
SELECT
    l.location_id,
    d.department_id,
    lower(
        regexp_replace(d.department_name, '[^0-9A-Za-z가-힣]+', '-', 'g')
    ) || '.' || l.location_id || '@placeholder.local' AS location_department_email,
    TRUE AS is_active
FROM location l
CROSS JOIN department d;

-- complaint_petition.location_department_id FK 복구
DO $$
BEGIN
    IF to_regclass('public.complaint_petition') IS NOT NULL THEN
        EXECUTE '
            ALTER TABLE complaint_petition
            ADD CONSTRAINT fk_complaint_petition_location_department
            FOREIGN KEY (location_department_id)
            REFERENCES location_department(location_department_id)
        ';
    END IF;
END $$;

COMMIT;
