BEGIN;

-- 1) 카테고리 마스터 (이미 존재하면 유지)
CREATE TABLE IF NOT EXISTS department (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(128) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL
);

-- 2) 시군구-카테고리 매핑 (이미 존재하면 유지)
CREATE TABLE IF NOT EXISTS location_department (
    location_department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL REFERENCES location(location_id),
    department_id BIGINT NOT NULL REFERENCES department(department_id),
    location_department_email VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL,
    CONSTRAINT uq_location_department_pair UNIQUE (location_id, department_id)
);

CREATE INDEX IF NOT EXISTS idx_location_department_location_id
    ON location_department (location_id);

CREATE INDEX IF NOT EXISTS idx_location_department_department_id
    ON location_department (department_id);

-- 3) 카테고리 시드 (중복 무시)
INSERT INTO department (department_name) VALUES
    ('건축허가'),
    ('경제'),
    ('공통'),
    ('교통'),
    ('농업_축산'),
    ('문화_체육_관광'),
    ('보건소'),
    ('복지'),
    ('산림'),
    ('상하수도'),
    ('세무'),
    ('안전건설'),
    ('위생'),
    ('자동차'),
    ('정보통신'),
    ('토지'),
    ('행정'),
    ('환경미화')
ON CONFLICT (department_name) DO NOTHING;

-- 4) location 전체 x category 전체 매핑 (중복 무시)
INSERT INTO location_department (
    location_id,
    department_id,
    location_department_email,
    is_active
)
SELECT
    l.location_id,
    d.department_id,
    lower(
        regexp_replace(d.department_name, '[^0-9A-Za-z가-힣]+', '-', 'g')
    ) || '.' || l.location_id || '@placeholder.local' AS location_department_email,
    TRUE AS is_active
FROM location l
CROSS JOIN department d
ON CONFLICT ON CONSTRAINT uq_location_department_pair DO NOTHING;

COMMIT;
