BEGIN;

-- ADMIN 권한 체크용 role 컬럼 (이미 있으면 유지)
ALTER TABLE "user"
    ADD COLUMN IF NOT EXISTS role VARCHAR(32);

UPDATE "user"
SET role = 'USER'
WHERE role IS NULL;

ALTER TABLE "user"
    ALTER COLUMN role SET DEFAULT 'USER';

ALTER TABLE "user"
    ALTER COLUMN role SET NOT NULL;

-- 1) 부서 마스터
CREATE TABLE IF NOT EXISTS department (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(128) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL
);

-- 2) 시군구-부서 매핑
CREATE TABLE IF NOT EXISTS location_department (
    location_department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL REFERENCES location(location_id),
    department_id BIGINT NOT NULL REFERENCES department(department_id),
    location_department_email VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL,
    CONSTRAINT uq_location_department_pair UNIQUE (location_id, department_id)
);

CREATE INDEX IF NOT EXISTS idx_location_department_location_id
    ON location_department (location_id);

CREATE INDEX IF NOT EXISTS idx_location_department_department_id
    ON location_department (department_id);

-- 3) 민원 신청 이력
CREATE TABLE IF NOT EXISTS complaint_petition (
    petition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_department_id BIGINT NOT NULL,
    issue_pin_id BIGINT NOT NULL,
    CONSTRAINT fk_complaint_petition_location_department
        FOREIGN KEY (location_department_id) REFERENCES location_department(location_department_id),
    CONSTRAINT fk_complaint_petition_issue_pin
        FOREIGN KEY (issue_pin_id) REFERENCES issue_pin(issue_pin_id),
    generated_on DATE NOT NULL,
    pdf_s3_key TEXT NOT NULL,
    pdf_s3_url TEXT NOT NULL,
    email_subject TEXT NOT NULL,
    email_body TEXT NOT NULL,
    reliability_score DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    reliability_basis TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NULL,
    CONSTRAINT uq_complaint_petition_issuepin_generatedon
        UNIQUE (issue_pin_id, generated_on),
    CONSTRAINT ck_complaint_petition_status
        CHECK (status IN ('CREATED', 'SENT', 'FAILED')),
    CONSTRAINT ck_complaint_petition_reliability_score
        CHECK (reliability_score >= 0.0 AND reliability_score <= 1.0)
);

CREATE INDEX IF NOT EXISTS idx_complaint_petition_location_department_id
    ON complaint_petition (location_department_id);

CREATE INDEX IF NOT EXISTS idx_complaint_petition_issue_pin_id
    ON complaint_petition (issue_pin_id);

CREATE INDEX IF NOT EXISTS idx_complaint_petition_generated_on
    ON complaint_petition (generated_on);

CREATE INDEX IF NOT EXISTS idx_complaint_petition_created_at
    ON complaint_petition (created_at DESC);

COMMIT;

